"""add repost tables

Revision ID: 571f2c1f0ad6
Revises: a4bedecaf610
Create Date: 2026-02-06 21:33:59.292104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '571f2c1f0ad6'
down_revision: Union[str, Sequence[str], None] = 'a4bedecaf610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repost_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('source_channel_title', sa.String(length=255), nullable=False),
    sa.Column('source_channel_username', sa.String(length=255), nullable=True),
    sa.Column('target_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('target_channel_title', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('check_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('last_processed_message_id', sa.Integer(), nullable=False),
    sa.Column('watermark_text', sa.Text(), nullable=True),
    sa.Column('repost_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('allowed_content_types', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_channel_id')
    )
    op.create_table('repost_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('source_message_id', sa.Integer(), nullable=False),
    sa.Column('target_message_id', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('reposted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['repost_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repost_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('total_reposts', sa.Integer(), nullable=False),
    sa.Column('successful_reposts', sa.Integer(), nullable=False),
    sa.Column('failed_reposts', sa.Integer(), nullable=False),
    sa.Column('filtered_posts', sa.Integer(), nullable=False),
    sa.Column('content_type_counts', sa.JSON(), nullable=False),
    sa.Column('last_repost_at', sa.DateTime(), nullable=True),
    sa.Column('stats_period_start', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['repost_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repost_stats')
    op.drop_table('repost_logs')
    op.drop_table('repost_configs')
    # ### end Alembic commands ###
